booktopia/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from booktopia import settings
from booktopia.common.views import landing_page

urlpatterns = [
    path('', landing_page, name='landing'),
    path('admin/', admin.site.urls, name='admin'),
    path('grappelli/', include('grappelli.urls')),  # grappelli URLS
    path('grappelli-docs/', include('grappelli.urls_docs')),  # grappelli docs URLS

    path('book/', include('booktopia.books.urls')),

    # TODO: A LE MERGER AVEC PROFILE
    path('owner/', include('booktopia.book_owners.urls')),
    path('account/', include('booktopia.accounts.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

booktopia/books/models.py
import os
import random
import string
from datetime import datetime

import qrcode
from django.contrib.auth import get_user_model
from django.core.validators import MinValueValidator
# from django.db import models
from django.utils.html import mark_safe  # for Image Tags and book previews
#
from taggit.managers import TaggableManager

from booktopia.book_owners.models import Owner
from booktopia.common.countries import LANGUAGES_BG
from booktopia.common.general_choices import BOOK_RELEASE, BOOK_CONDITION, BOOK_CURRENT_STATUS
from booktopia.settings import MEDIA_ROOT
# IMPORTING SPLITED INITIAL MODEL FILE
#
from .submodels.authors_model import *
from .submodels.editions_model import *
from .submodels.status_model import *

#


UserModel = get_user_model()


class Book(models.Model):
    # Section Nom
    user = models.ForeignKey(
        UserModel,
        on_delete=models.CASCADE,
        default=1,
        verbose_name='Потребител'
    )

    name = models.CharField(max_length=200, verbose_name='Име на книгата')

    editions = models.ForeignKey(Editions, on_delete=models.DO_NOTHING,
                                 verbose_name='Издателска къща', default='')

    series = models.CharField(max_length=100, verbose_name='Поредица',
                              null=True, blank=True)

    translated = models.BooleanField(default=False, verbose_name='Преведена')

    original_name = models.CharField(max_length=200, verbose_name='Оригинално име', blank=True)

    edition_lang = models.CharField(max_length=3, choices=LANGUAGES_BG,
                                    verbose_name='Език на изданието',
                                    default='Български език',
                                    blank=True)

    edition_lang_orig = models.CharField(max_length=3, choices=LANGUAGES_BG,
                                         verbose_name='Оригинален Език',
                                         blank=True)

    book_current_status = models.CharField(max_length=25, default='F',
                                           verbose_name='Актуално състояние на книгата',
                                           choices=BOOK_CURRENT_STATUS)

    catalog_num = models.CharField(max_length=100, verbose_name='Вътрешен каталожен номер',
                                   null=True, blank=True,
                                   help_text="Каталожен номер по десетична система. Полето е задължително",
                                   default=None)

    isbn_code = models.CharField(max_length=15, verbose_name='ISBN', blank=True, null=True)

    oclc_code = models.CharField(max_length=15, verbose_name='OCLC', blank=True, null=True)

    synopsis = models.TextField(blank=True, null=True, verbose_name='Синопсис')
    notes = models.TextField(blank=True, null=True, verbose_name='Бележка')

    release_year = models.PositiveSmallIntegerField(verbose_name='Година на изданието', blank=True, null=True)

    release_number = models.PositiveSmallIntegerField(choices=BOOK_RELEASE, verbose_name='Издание', blank=True,
                                                      default=1, null=True, help_text='Поредно Издание')

    pages_count = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name='Брой Страници')
    measure_x = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name='Ширина (cм)')
    measure_y = models.PositiveSmallIntegerField(null=True, blank=True, verbose_name='Височина (cм)')
    weight_grams = models.PositiveSmallIntegerField(default=250, blank=True, verbose_name='Тегло Грама')

    # TODO - a le faire en Foreign
    visual_condition = models.PositiveSmallIntegerField(choices=BOOK_CONDITION,
                                                        verbose_name='Състояние',
                                                        default=1,
                                                        null=True)

    record_created_at = models.DateTimeField(auto_now_add=True, blank=True,
                                             null=True, verbose_name='Дата на създаване на записа')
    record_updated_at = models.DateTimeField(auto_now=True, blank=True,
                                             null=True, verbose_name='Дата на промяна на записа')

    # TODO: a lier avec les wish lists
    book_to_read_by_owner = models.BooleanField(default=False, verbose_name='Непрочетена')

    price_for_rent = models.FloatField(default=1.00,
                                       verbose_name='Стойност на гаранцията (лв.)',
                                       validators=[MinValueValidator(1.0,
                                                                     message='Минималната гараранция е 1,00 лев.')])
    price_for_sell = models.FloatField(blank=True, null=True,
                                       verbose_name='Цена за продажба (лв.)',
                                       validators=[MinValueValidator(1.2, message='Минималната цена е 1,20 лева.')])

    # BOOLS
    is_hidden = models.BooleanField(default=False, verbose_name='Не показвай в Booktopia (скрита)')
    is_archived = models.BooleanField(default=False, verbose_name='Книгата е архивирана')
    is_for_sale = models.BooleanField(default=False, verbose_name='Обявена за продажба')
    is_sold = models.BooleanField(default=False, verbose_name='Книгата е продадена')
    is_lost = models.BooleanField(default=False, verbose_name='Книгата е загубена')

    # FIXME: to be removed or integrated in the general status
    book_reserved = models.BooleanField(default=False, verbose_name='Резервирана')

    # FIXME - on le update ou on le calcume selon l'histoire du truc
    has_been_rented_times = models.PositiveSmallIntegerField(blank=True, verbose_name='Заемана пъти', null=True)

    # Uploading each file in a separate file path by a pk and book name
    def file_upload_path(self, filename):
        book_id = str(self.catalog_num)
        # book_id = str(self.pk)
        return "book_images/" + book_id + "/" + filename

    cover_front = models.ImageField(upload_to=file_upload_path, verbose_name='Корица',
                                    null=True, blank=True,
                                    default='/static/generic/generic-book-2.png'
                                    # help_text="Моля, изберете снимка"
                                    )

    cover_back = models.ImageField(upload_to=file_upload_path, verbose_name='Гръб',
                                   null=True, blank=True,
                                   default='/static/generic/generic-book-2.png'
                                   # help_text="Моля, изберете снимка"
                                   )

    #
    #
    #
    #
    @property
    def cover_front_url(self):
        try:
            url = self.cover_front.url
        except:
            url = 'generic/generic-book-2.png'
        return url

    @property
    def cover_back_url(self):
        try:
            url = self.cover_back.url
        except:
            url = 'generic/generic-book-2.png'
        return url

    # FIXME: a voir comment le manque d'image joue dans l'admin
    def image_cover_front(self):
        if self.cover_front:
            return mark_safe('<img src="/media_upload/%s" width="150" height="200" />' % self.cover_front)

    def image_cover_back(self):
        if self.cover_back:
            return mark_safe('<img src="/media_upload/%s" width="150" height="200" />' % self.cover_back)

    image_cover_front.short_description = 'Преглед корица: (150*200)'
    image_cover_back.short_description = 'Преглед гръб: (150*200)'

    generated_qr_code_image = models.ImageField(upload_to=file_upload_path,
                                                verbose_name='Автоматичен QR Код', null=True,
                                                blank=True, )


    # FIXME: a le faire en readonly ou le cacher
    generated_qr_code_content = models.CharField(max_length=100, default=None,
                                                 null=True, blank=True, )
    tags = TaggableManager(blank=True,
                           verbose_name='Тагове, разделени със запетайка', )
    #
    # Foreign keys
    author_name = models.ForeignKey(Author, on_delete=models.RESTRICT,
                                    null=True, verbose_name='Автор(и)')

    # book_rent_history = models.ForeignKey(RentHistory, on_delete=models.RESTRICT,
    #                                       verbose_name='История на заеманията', blank=True, null=True)
    book_transportation_history = models.ForeignKey(StatusHistory, on_delete=models.RESTRICT,
                                                    verbose_name='История на транспортиранията', blank=True, null=True)

    # book_reviews = models.ForeignKey(Reviews, on_delete=models.CASCADE,
    #                                  verbose_name='Ревюта', blank=True, null=True)

    # owner = models.ForeignKey(Owner, on_delete=models.RESTRICT,
    #                           verbose_name='Собственик', null=True)

    #
    # Random string generator for the QR code
    def qr_code_gen(self, request_type=None):
        cat = 'bt01'
        range_low = 1000000
        range_high = 9999999
        checksum = str(random.randint(range_low, range_high))
        chars = string.ascii_uppercase
        random_string = (''.join(random.choice(chars) for _ in range(7)))
        date_time = datetime.now()

        # https://docs.python.org/3/library/datetime.html
        if request_type == "barcode":
            # TODO: Ajouter un URL pour la suite ici (reste a savoir ou il sera loge)
            return f'{cat}|{checksum}{random_string}|{str(date_time.strftime("%a_%m_%B_%Y_%H_%M_%S")).upper()}'
        elif request_type == "checksum":
            return (cat + checksum + random_string).upper()
        else:
            return ''

    def qr_picture_gen(self, qr_code_content=None):
        qrc = qrcode.QRCode(
            version=1,
            error_correction=qrcode.constants.ERROR_CORRECT_M,

booktopia/books/forms/author_add_form.py
from django import forms


class AuthorAddForm(forms.Form):
    first_name = forms.CharField(max_length=25)
    last_name = forms.CharField(max_length=25)
    pseudonym = forms.CharField(max_length=25)
    date_of_birth = forms.DateField(required=False)
    date_of_death = forms.DateField(required=False)
    wiki_page = forms.URLField(required=False)

templates/authors/author_add.html
{% extends 'core_template.html' %}
{% load widget_tweaks %}

{% block meta_description %}{% endblock %}
{% block meta_content %}{% endblock %}
{% block title %}Добави нов автор{% endblock %}

{% block css_head %}
    <link rel="stylesheet" href="/static/css/bootstrap-tagsinput.css"/>
{% endblock %}

{% block content_main %}

    <div class="container">
        <form action="{% url 'add new author' %}"
              class="w-50 m-auto needs-validation"
              method="post">

            <div class="text-center mt-2 mb-2 text-warning"
                 style="height: 50px;">
                <h4>Всички полета са задължителни</h4>
            </div>

            {% csrf_token %}
            {{ form }}
            {{ form.errors }}

            <div class="text-center mt-4">
                <button type="submit" class="btn btn-rounded btn-outline-primary">Добави нов автор</button>
            </div>
        </form>
    </div>

{% endblock %}

templates/authors/author_delete.html
{% extends 'core_template.html' %}
{#{% load widget_tweaks %}#}

{% block meta_description %}{% endblock %}
{% block meta_content %}{% endblock %}

{% block title %}Изтриване на автор{% endblock %}

{% block content_main %}
    <div class="row">
        <div class="col-lg-12 text-center">
            <h1>Сигурни ли сте, че желаете да изтриете
                <br>{{ author.first_name }} {{ author.last_name }}?</h1>
            <h2>Това действие е необратимо...</h2>

            <div class="m-auto d-flex justify-content-center">
                <div class="m-2">
                    <form method="post">
                        {% csrf_token %}
                        <input type="submit" value="Да, един автор напуска света на Booktopia" class="btn btn-danger"/>
                    </form>
                </div>

                <div class="m-2">
                    <a class="btn btn-primary" href="javascript:history.back()">Не</a>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

templates/authors/author_detail.html
{% extends 'core_template.html' %}
{% load static %}

{% block meta_description %}{% endblock %}
{% block meta_content %}{% endblock %}

{% block title %}Детайлна информация за книга{% endblock %}

{% block content_main %}

    <!-- Tabs navs -->
    <ul class="nav nav-tabs nav-justified mb-3" id="tab_book" role="tablist">
        <li class="nav-item" role="presentation">
            <a class="nav-link active"
               id="ex3-tab-1"
               data-mdb-toggle="tab"
               href="#ex3-tabs-1"
               role="tab"
               aria-controls="ex3-tabs-1"
               aria-selected="true">Обща информация</a>
        </li>


        <li class="nav-item" role="presentation">
            <a class="nav-link"
               id="ex3-tab-2"
               data-mdb-toggle="tab"
               href="#ex3-tabs-2"
               role="tab"
               aria-controls="ex3-tabs-2"
               aria-selected="false">Произведения</a>
        </li>

        <li class="nav-item" role="presentation">
            <a class="nav-link"
               id="ex3-tab-3"
               data-mdb-toggle="tab"
               href="#ex3-tabs-3"
               role="tab"
               aria-controls="ex3-tabs-3"
               aria-selected="false">Коментари</a>
        </li>

    </ul>
    <!-- Tabs -->

    <!-- Tabs content -->
    <div class="tab-content" id="ex2-content">
        <div class="tab-pane fade show active"
             id="ex3-tabs-1"
             role="tabpanel"
             aria-labelledby="ex3-tab-1">

            {# Section Info 1 #}
            <div class="container align-content-md-center text-center mt-5">
                <div class="row">
                    <div class="col-md">
                        <p>Име</p>
                        <h4>{{ author.first_name|upper }}</h4>
                    </div>
                    <div class="col-md">
                        <p>Фамилия</p>
                        <h4>{{ author.last_name|title }}</h4>
                    </div>
                    <div class="col-md">
                        <p>Псевдоним</p>
                        <h4>{{ author.pseudonym|default_if_none:"Няма"|title }}</h4>
                    </div>
                </div>
            </div>

            <hr>

            {# Section Info 1 #}
            <div class="container align-content-md-center text-center mt-5">
                <div class="row">
                    <div class="col-md">
                        <p>Дата на раждане</p>
                        <h4>{{ author.date_of_birth|upper|default_if_none:'Не е въведена' }}</h4>
                    </div>
                    <div class="col-md">
                        <p>Починал</p>
                        <h4>{{ author.date_of_death|default_if_none:'' }}</h4>
                    </div>
                    <div class="col-md">
                        <p>Възраст</p>
                        <h4>{{ author.author_calculated_age|default_if_none:"~" }}</h4>
                    </div>
                </div>
            </div>
            <hr>

            {# Section Info 3 #}
            <div class="container align-content-md-center text-center mt-lg-4">
                <div class="row">

                    <div class="col-md">
                        <p>Линк с допълнителна информация</p>

                        {% if author.wiki_page %}
                            <a href="{{ author.wiki_page }}" target="_blank">{{ author.wiki_page }}</a>
                        {% else %}
                            <strong>Няма</strong>
                        {% endif %}
                    </div>

                    {# TODO: a fixer la liste #}
                    <div class="col-md">
                        <p>Националност</p>
                        <h4>{{ author.nationality|default_if_none:"~" }}</h4>
                    </div>

                </div>
            </div>
            <hr>

            {# Modify book info form button #}
            <div class="d-flex flex-column mb-3 align-items-center">
                <div class="p-2 align-items-center">
                    <a href="{% url 'edit author' author.id %}" class="btn btn-outline-dark ">
                        Промени Данните за автора
                    </a>
                </div>
            </div>

            {# Delete book #}
            <div class="d-flex flex-column mb-3 align-items-center">
                <div class="p-2 align-items-center">
                    <a href="{% url 'delete author' author.id %}" class="btn-danger btn-outline-dark ">
                        Изтрий автора
                    </a>
                </div>
            </div>
        </div>


        {# TAB 2 content #}
        <div class="tab-pane fade"
             id="ex3-tabs-2"
             role="tabpanel"
             aria-labelledby="ex3-tab-2">

            <table class="table table-sm table-hover table-bordered">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">id</th>
                        <th scope="col">книга</th>
                        <th scope="col">Издателство</th>
                        <th scope="col">Година</th>
                        <th scope="col">Статус</th>
                        <th scope="col">Състояние</th>
                    </tr>
                    </thead>

                    <tbody>

                    {% for el in books %}
                        <tr>
                            <th scope="row">{{ el.pk }}</th>

                            <td class=""><strong>
                                <a href="{% url 'book detail' el.pk %}">{{ el.name|upper }}</a>
                            </strong></td>

                            <td class=""><strong>
                                <a href="{% url 'edition detail' el.editions.pk %}">{{ el.editions|upper }}</a>
                            </strong></td>

                            <td>{{ el.release_year|default_if_none:'неизвестна' }}</td>
                            <td>{{ el.get_book_current_status_display|default_if_none:'без' }}</td>
                            <td>{{ el.get_visual_condition_display|default_if_none:'без' }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>

        </div>

        {# TAB 3 content #}
        <div class="tab-pane fade"
             id="ex3-tabs-3"
             role="tabpanel"
             aria-labelledby="ex3-tab-3">

            <div class="container">
                {% for el in comments %}
                    <table class="table table-sm table-hover table-bordered mb-5">
                        <thead class="table-dark">
                        <tr>
                            <th scope="col">от: {{ el.user_id }}</th>
                            <th scope="col">на дата: {{ el.record_created_at }}</th>
                        </tr>
                        </thead>

                        <tbody>
                        <tr class="table-light">
                            {# <th scope="row">3</th> #}
                            <td colspan="2">{{ el.comment }}</td>
                        </tr>
                        </tbody>
                    </table>
                {% endfor %}
            </div>

            <form action="{% url 'new comment author' author.pk %}" class="w-50 m-auto" method="post">
                {% csrf_token %}
                {{ form }}
                {{ form.errors }}

                <div class="text-center mt-4">
                    <button type="submit" class="btn btn-rounded btn-outline-primary">Добави нов коментар</button>
                </div>
            </form>

        </div>

    </div>
    <!-- Tabs content -->

{% endblock %}

templates/authors/author_edit.html
{% extends 'core_template.html' %}
{% load widget_tweaks %}

{% block meta_description %}{% endblock %}
{% block meta_content %}{% endblock %}
{% block title %}Промени данни на автор{% endblock %}

{#{% block css_head %}#}
{#    <link rel="stylesheet" href="/static/css/bootstrap-tagsinput.css"/>#}
{#{% endblock %}#}

{% block content_main %}

    <div class="container">
        <form action="{% url 'edit author' author.pk %}"
              class="w-50 m-auto needs-validation"
              method="post">

            <div class="text-center mt-2 mb-2 text-warning"
                 style="height: 50px;">
                <h4>Всички полета са задължителни</h4>
            </div>


            {% csrf_token %}
            {{ form }}
            {{ form.errors }}

            <div class="text-center mt-4">
                <button type="submit" class="btn btn-rounded btn-outline-primary">Промени данните</button>
            </div>

            <div class="m-2 text-center">
                <a class="btn btn-outline-black btn-rounded" href="javascript:history.back()">Назад</a>
            </div>
        </form>
    </div>

{% endblock %}

templates/authors/authors_all.html
{% extends 'core_template.html' %}
{% load static %}

{% block meta_description %}{% endblock %}
{% block meta_content %}{% endblock %}
{% block title %}Всички автори{% endblock %}



{% block content_main %}

    {# Add new book button   #}
    <div class="d-flex flex-column mb-3 align-items-center">
        <div class="p-2">
            <a href="{% url 'add new author' %}" class="btn btn-outline-dark ">
                {% if author.count == 0 %}
                    Добави пътвият автор в Буктопия!
                {% else %}
                    Добави нов автор
                {% endif %}
            </a>
        </div>
    </div>



    {# Table #}
    <table class="table table-sm table-hover table-bordered">
        <thead class="thead-dark">
        <tr>
            <th scope="col">id</th>
            <th scope="col">Име</th>
            <th scope="col">Фамилия</th>
            <th scope="col">Псевдоним</th>
            <th scope="col">Дата на раждане</th>
            <th scope="col">Брой книги тук</th>
        </tr>
        </thead>
        <tbody>

        {% for i in author %}
            <tr>
                <th scope="row">{{ i.pk }}</th>
                <td class=""><strong>
                    <a href="{% url 'author detail' i.pk %}">{{ i.first_name.upper }}</a>
                </strong></td>

                <td>{{ i.last_name }}</td>
                <td>{{ i.pseudonym|default_if_none:"няма" }}</td>
                <td>{{ i.date_of_birth|default_if_none:'неизвестна' }}</td>

                <td>{{ i.author_book_count|default_if_none:'без' }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% include 'elements/el_paginator.html' %}

{% endblock %}